### ISSUE TITLE
SunOS lacks BSD sig_t type

### ISSUE THREAD

**Issue by tnn2** [outpaddling/libxtend#1]
Caught by pkgsrc bulk builds:
```
spawnvp.c: In function 'spawnvp':
spawnvp.c:64:5: error: unknown type name 'sig_t'
   64 |     sig_t   oldsig;
      |     ^~~~~
```

My suggested fix is to to place in top of spawnvp.c:
```
#if defined(__sun__)
typedef void (*sig_t)(int);
#endif
```

Please also update the pkgsrc package.

**Comment by outpaddling** [comment]
Are you certain that SunOS does not have sig_t defined in a header somewhere?  I would assume you tried

grep -r sig_t /usr/include

I'd expect signal.h to be sufficient, but who knows...

If it's not, I'd be inclined to revamp the code to use a more portable interface.

**Comment by tnn2** [comment]
Neither `sig_t` nor `sigaction_t` are available AFAICT.
POSIX doesn't speficy these types, they are BSD and Linux extensions, respectively.
(But Linux provides the BSD compatibility type.)

**Comment by outpaddling** [comment]
I installed OpenIndiana minimal under VirtualBox, but I'm having trouble determining what the "default" compiler is.  It seems that GCC is the mainstream, but which version I'm not sure.

**Comment by tnn2** [comment]
`pkg install developer/gcc-10` should be OK. It is what I use.

**Comment by outpaddling** [comment]
```
root@sunfish:~# pkg install developer/gcc-10
Creating Plan (Solver setup): -
pkg install: No matching version of developer/gcc-10 can be installed:
  Reject:  pkg://openindiana.org/developer/gcc-10@10.3.0-2020.0.1.3
  Reason:  No version matching 'require' dependency developer/gnu-binutils can be installed
    ----------------------------------------
    Reject:  pkg://openindiana.org/developer/gnu-binutils@2.38-2022.0.0.0
             pkg://openindiana.org/developer/gnu-binutils@2.38-2022.0.0.0
    Reason:  This version is excluded by installed incorporation consolidation/userland/userland-incorporation@0.5.11-2020.0.1.14595
    ----------------------------------------

```

**Comment by tnn2** [comment]
Not sure -- maybe do `pkg update` first. Looks like things might be outdated.

**Comment by outpaddling** [comment]
Yeah, I tried that as a shot in the dark last night.  After rebooting this morning it worked.  Presumably needed to load the new boot env after the update.

**Comment by outpaddling** [comment]
For now I added the sig_t def as a hack.  The pkg is in wip.

A pkgsrc issue on OpenIndiana:

=> Checking for SSP in digest-20220214
ERROR: bin/digest: missing SSP
*** Error code 1

Stop.
bmake[2]: stopped in /export/home/bacon/Pkgsrc/pkgsrc/pkgtools/digest
*** Error code 1

I worked around it by setting PKGSRC_USE_SSP=no in mk.conf.  Have you seen this?  If not, I'll ping pkgsrc-users.

**Comment by tnn2** [comment]
I have the same setting in my mk.conf. I think I just concluded that the distribution compiler probably has some things disabled. Regardless we should improve the error message and/or the bootstrap and/or figure out why this doesn't work when it does on other SunOS derivatives.

**Comment by outpaddling** [comment]
Another update to libxtend is in pkgsrc/wip now.  I got all of my active projects to build cleanly on OpenIndiana, working around a few limitations and peculiarities:

1.  Unclear what the mainstream compiler is
    pkg update
    reboot      # Must load new boot env before pkg will work
    pkg install developer/gcc-10

2.  No cc command, though there is a /usr/bin/c++
    Hacked around with ln -s gcc cc

3.  /bin/sh does not support local variables

4.  /usr/sbin/install cannot handle multiple files / wildcards
    Hacked around using pkgsrc bsdinstall and ln -s bsdinstall install

5.  make does not support ?=
     Using gmake

7.  No dprintf() function
    Added xt_dprintf() to libxtend
